stages:
  - crossCompile

crossCompile:
  variables:
    GOPROXY: "https://goproxy.cn,direct"
    GOPATH: "/go"
    GOROOT: "/usr/local/go"
  image:
    name: karalabe/xgo-latest
    entrypoint: [ "" ]
  stage: crossCompile
  script:
    - wget https://golang.google.cn/dl/go1.17.6.linux-amd64.tar.gz
    - rm -rf /usr/local/go
    - tar -C /usr/local -zxvf  go1.17.6.linux-amd64.tar.gz
    - export GOPROXY=https://goproxy.cn,direct
    - mkdir build
    - xgo -pkg=/node --targets=linux/amd64  .
    - mv /build/node-linux-amd64 ./build/node
    - go build
    - mv ./witCon ./build/witcon
    - ls ./build
  artifacts:
    expire_in: 30 days
    paths:
      - ./build
  only:
    - develop