path = "E:\\wit-cons\\p2-240614"
nodePath = "D:\\go_workspace\\witCon"
IP = "192.168.1.52"
nodeName = "node.exe"
nodes = 4
logLvl = 2
consensus = 1
txAmount = 20000
txSize = 200000
viewChangeDuration = 20000
rtt = 0
prePack = true
shardVerify = true
schnorr = true
signVerifyCore = 20
shardCount = 4
shardVerifyCore = 4
VerifyCount = 0